/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hanoi;

import Hanoi.Hanoi;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Random;
import javax.swing.*;
import javax.swing.Timer;

/**
 *
 * @author chiza
 */
public class InterfazHanoi extends javax.swing.JFrame {

    private int numDiscos, numPostes;
    private Hanoi hanoi;
    private JPanel[] panelesTorres;
    private JLabel[] palos;
    private Stack<Integer>[] torres;
    private List<int[]> movimientos;
    private int pasoActual = 0;
    private Timer timer;
    private Color[] discoColors;

    /**
     * Creates new form InterfazHanoi
     */
    public InterfazHanoi() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPalo = new javax.swing.JTextField();
        txtDisco = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Palo:");

        jLabel2.setText("Disco:");

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPalo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGo)
                        .addGap(96, 96, 96))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtPalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        numDiscos = Integer.parseInt(txtDisco.getText());
        numPostes = Integer.parseInt(txtPalo.getText());

        if (numPostes < 3 || numDiscos < 1) {
            JOptionPane.showMessageDialog(this, "Debe haber al menos 3 palos y 1 disco.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        hanoi = new Hanoi(numDiscos, numPostes);
        movimientos = hanoi.resolver();
        discoColors = new Color[numDiscos];
        Random rand = new Random();

        for (int i = 0; i < numDiscos; i++) {
            discoColors[i] = new Color(rand.nextInt(256), rand.nextInt(256), rand.nextInt(256));
        }

        iniciarTorres();
        timer = new Timer(400, this::mostrarSiguienteMovimiento);
        timer.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoActionPerformed

    private void iniciarTorres() {
        Background.removeAll();
        Background.setLayout(new GridLayout(1, numPostes));

        torres = new Stack[numPostes];
        panelesTorres = new JPanel[numPostes];
        palos = new JLabel[numPostes];

        for (int i = 0; i < numPostes; i++) {
            torres[i] = new Stack<>();
            panelesTorres[i] = new JPanel(null);
            panelesTorres[i].setPreferredSize(new Dimension(120, 300));
            panelesTorres[i].setBackground(Color.WHITE);

            palos[i] = new JLabel();
            palos[i].setOpaque(true);
            palos[i].setBackground(Color.BLACK);
            palos[i].setBounds(50, 50, 10, 200);
            panelesTorres[i].add(palos[i]);

            Background.add(panelesTorres[i]);
        }

        for (int i = numDiscos; i > 0; i--) {
            torres[0].push(i);
        }

        actualizarInterfaz();
        Background.revalidate();
        Background.repaint();
    }

    private void mostrarSiguienteMovimiento(ActionEvent e) {
        if (pasoActual < movimientos.size()) {
            int[] mov = movimientos.get(pasoActual++);
            int origen = mov[0];
            int destino = mov[1];

            if (!torres[origen].isEmpty()) {
                int disco = torres[origen].pop();
                torres[destino].push(disco);
                actualizarInterfaz();
            }
        } else {
            timer.stop();
        }
    }

    private void actualizarInterfaz() {
        for (int i = 0; i < numPostes; i++) {
            panelesTorres[i].removeAll();
            panelesTorres[i].add(palos[i]);

            int yPos = 250;
            for (int disco : torres[i]) {
                JLabel lblDisco = new JLabel();
                lblDisco.setOpaque(true);
                lblDisco.setBackground(discoColors[disco - 1]);
                lblDisco.setHorizontalAlignment(SwingConstants.CENTER);
                lblDisco.setForeground(Color.WHITE);

                int ancho = 20 * disco;
                lblDisco.setBounds(60 - (ancho / 2), yPos, ancho, 20);
                yPos -= 25;

                panelesTorres[i].add(lblDisco);
            }

            panelesTorres[i].revalidate();
            panelesTorres[i].repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazHanoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDisco;
    private javax.swing.JTextField txtPalo;
    // End of variables declaration//GEN-END:variables
}
